[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']

# RPC URL for Sepolia testnet (or use environment variable SEPOLIA_RPC_URL)
# If you need to fork Sepolia for tests, you can use: --fork-url $SEPOLIA_RPC_URL
# For Sepolia, use: https://eth-sepolia.g.alchemy.com/v2/YOUR_API_KEY
# Note: The URL you provided is for mainnet, update it for Sepolia if needed

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
